// ---------------------------------------------------------------
// AUTO-GENERATED by scripts/sync-products.mjs. Do not hand-edit.
// Split out from products-data.js so pages that only need the category
// list (every product detail page) don't have to load the whole catalog.
// ---------------------------------------------------------------

// Canonical category list — a product can belong to more than one.
const CATEGORIES = [
  "Painting sketch",
  "Resin art",
  "Lippan art",
  "Mosaic art",
  "Home deco",
  "Festival special",
  "Gift",
  "Mirror"
];
