// ---------------------------------------------------------------
// AUTO-GENERATED by scripts/sync-products.mjs from the operator's
// Google Sheet + Drive photos. Do not hand-edit — changes here get
// overwritten on the next sync. To update products, edit the sheet.
// Last synced: 2026-09-25T08:32:52.370Z
// ---------------------------------------------------------------

const PRODUCTS = [
  {
    "id": "resin-keychain",
    "name": "Resin Keychain",
    "price": "₹299",
    "originalPrice": "",
    "description": "Handmade resin keychain ✨ Customizable, stylish & perfect for gifting or everyday use. 💖",
    "size": "",
    "image": "resin-keychain.jpg",
    "imageSmall": "resin-keychain-sm.jpg",
    "extraImages": [
      {
        "image": "resin-keychain-alt1.jpg",
        "imageSmall": "resin-keychain-alt1-sm.jpg"
      },
      {
        "image": "resin-keychain-alt2.jpg",
        "imageSmall": "resin-keychain-alt2-sm.jpg"
      },
      {
        "image": "resin-keychain-alt3.jpg",
        "imageSmall": "resin-keychain-alt3-sm.jpg"
      }
    ],
    "categories": [
      "Resin art",
      "Gift"
    ],
    "whatsappMessage": "buy resin Keychain"
  },
  {
    "id": "resin-keychain-2",
    "name": "Resin Keychain",
    "price": "₹299",
    "originalPrice": "",
    "description": "Handmade resin keychain ✨ Customizable, stylish & perfect for gifting or everyday use. 💖",
    "size": "",
    "image": "resin-keychain-2.jpg",
    "imageSmall": "resin-keychain-2-sm.jpg",
    "extraImages": [
      {
        "image": "resin-keychain-2-alt1.jpg",
        "imageSmall": "resin-keychain-2-alt1-sm.jpg"
      }
    ],
    "categories": [
      "Resin art",
      "Gift"
    ],
    "whatsappMessage": "buy resin Keychain"
  },
  {
    "id": "resin-keychain-3",
    "name": "Resin Keychain",
    "price": "₹299",
    "originalPrice": "",
    "description": "Handmade resin keychain ✨ Customizable, stylish & perfect for gifting or everyday use. 💖",
    "size": "",
    "image": "resin-keychain-3.jpg",
    "imageSmall": "resin-keychain-3-sm.jpg",
    "extraImages": [
      {
        "image": "resin-keychain-3-alt1.jpg",
        "imageSmall": "resin-keychain-3-alt1-sm.jpg"
      }
    ],
    "categories": [
      "Resin art",
      "Gift"
    ],
    "whatsappMessage": "buy resin Keychain"
  },
  {
    "id": "resin-keychain-4",
    "name": "Resin Keychain",
    "price": "₹299",
    "originalPrice": "",
    "description": "Handmade resin keychain ✨ Customizable, stylish & perfect for gifting or everyday use. 💖",
    "size": "",
    "image": "resin-keychain-4.jpg",
    "imageSmall": "resin-keychain-4-sm.jpg",
    "extraImages": [
      {
        "image": "resin-keychain-4-alt1.jpg",
        "imageSmall": "resin-keychain-4-alt1-sm.jpg"
      }
    ],
    "categories": [
      "Resin art",
      "Gift"
    ],
    "whatsappMessage": "buy resin Keychain"
  },
  {
    "id": "resin-keychain-5",
    "name": "Resin Keychain",
    "price": "₹299",
    "originalPrice": "",
    "description": "Handmade resin keychain ✨ Customizable, stylish & perfect for gifting or everyday use. 💖",
    "size": "",
    "image": "resin-keychain-5.jpg",
    "imageSmall": "resin-keychain-5-sm.jpg",
    "extraImages": [
      {
        "image": "resin-keychain-5-alt1.jpg",
        "imageSmall": "resin-keychain-5-alt1-sm.jpg"
      },
      {
        "image": "resin-keychain-5-alt2.jpg",
        "imageSmall": "resin-keychain-5-alt2-sm.jpg"
      }
    ],
    "categories": [
      "Resin art",
      "Gift"
    ],
    "whatsappMessage": "buy resin Keychain"
  },
  {
    "id": "mirror",
    "name": "Mirror",
    "price": "₹2,499",
    "originalPrice": "",
    "description": "Handcrafted mirror with a stylish, elegant finish—perfect for adding a premium touch to your space. ✨",
    "size": "",
    "image": "mirror.jpg",
    "imageSmall": "mirror-sm.jpg",
    "extraImages": [
      {
        "image": "mirror-alt1.jpg",
        "imageSmall": "mirror-alt1-sm.jpg"
      }
    ],
    "categories": [
      "Resin art",
      "Home deco",
      "Festival special",
      "Gift",
      "Mirror"
    ],
    "whatsappMessage": "buy mirror"
  },
  {
    "id": "birds-berries-wall-decor",
    "name": "“Birds & Berries Wall Decor”.",
    "price": "₹999",
    "originalPrice": "",
    "description": "Colorful Bird & Cherry Wall Hanging 🐦🍒",
    "size": "",
    "image": "birds-berries-wall-decor.jpg",
    "imageSmall": "birds-berries-wall-decor-sm.jpg",
    "extraImages": [
      {
        "image": "birds-berries-wall-decor-alt1.jpg",
        "imageSmall": "birds-berries-wall-decor-alt1-sm.jpg"
      }
    ],
    "categories": [
      "Resin art",
      "Home deco",
      "Gift"
    ],
    "whatsappMessage": "buy hurry up"
  },
  {
    "id": "photo-preserve",
    "name": "Photo preserve",
    "price": "₹449",
    "originalPrice": "",
    "description": "your special memories beautifully preserved in a timeless resin keepsake. ✨",
    "size": "",
    "image": "photo-preserve.jpg",
    "imageSmall": "photo-preserve-sm.jpg",
    "extraImages": [
      {
        "image": "photo-preserve-alt1.jpg",
        "imageSmall": "photo-preserve-alt1-sm.jpg"
      }
    ],
    "categories": [
      "Resin art",
      "Home deco",
      "Gift"
    ],
    "whatsappMessage": "buy for your love one."
  },
  {
    "id": "resin-bangle",
    "name": "Resin bangle",
    "price": "₹399",
    "originalPrice": "",
    "description": "Add a touch of elegance to your look with our beautiful handcrafted Resin Bangle. Each bangle is carefully made with high-quality resin, beautiful colours and artistic detailing",
    "size": "",
    "image": "resin-bangle.jpg",
    "imageSmall": "resin-bangle-sm.jpg",
    "extraImages": [
      {
        "image": "resin-bangle-alt1.jpg",
        "imageSmall": "resin-bangle-alt1-sm.jpg"
      },
      {
        "image": "resin-bangle-alt2.jpg",
        "imageSmall": "resin-bangle-alt2-sm.jpg"
      },
      {
        "image": "resin-bangle-alt3.jpg",
        "imageSmall": "resin-bangle-alt3-sm.jpg"
      }
    ],
    "categories": [
      "Resin art",
      "Gift"
    ],
    "whatsappMessage": "buy resin bangle"
  },
  {
    "id": "book-mark",
    "name": "Book mark 💜",
    "price": "₹399",
    "originalPrice": "",
    "description": "beautiful and unique way to mark your favourite pages with elegance. ✨📖",
    "size": "",
    "image": "book-mark.jpg",
    "imageSmall": "book-mark-sm.jpg",
    "extraImages": [],
    "categories": [
      "Resin art",
      "Gift"
    ],
    "whatsappMessage": "buy bookmark"
  },
  {
    "id": "book-mark-2",
    "name": "Book mark",
    "price": "₹299",
    "originalPrice": "",
    "description": "beautiful and unique way to mark your favourite pages with elegance. ✨📖",
    "size": "",
    "image": "book-mark-2.jpg",
    "imageSmall": "book-mark-2-sm.jpg",
    "extraImages": [],
    "categories": [
      "Resin art",
      "Gift"
    ],
    "whatsappMessage": "buy bookmark"
  },
  {
    "id": "book-mark-3",
    "name": "Book mark 🌊",
    "price": "₹399",
    "originalPrice": "",
    "description": "beautiful and unique way to mark your favourite pages with elegance. ✨📖",
    "size": "",
    "image": "book-mark-3.jpg",
    "imageSmall": "book-mark-3-sm.jpg",
    "extraImages": [],
    "categories": [
      "Resin art",
      "Gift"
    ],
    "whatsappMessage": "buy bookmark"
  },
  {
    "id": "poja-thali",
    "name": "Poja Thali ❤️",
    "price": "₹549",
    "originalPrice": "",
    "description": "size 4.5 inches aesthetic designs for poja ghar",
    "size": "",
    "image": "poja-thali.jpg",
    "imageSmall": "poja-thali-sm.jpg",
    "extraImages": [
      {
        "image": "poja-thali-alt1.jpg",
        "imageSmall": "poja-thali-alt1-sm.jpg"
      }
    ],
    "categories": [
      "Resin art",
      "Home deco",
      "Festival special",
      "Gift"
    ],
    "whatsappMessage": "buy poja thali"
  },
  {
    "id": "poja-thali-2",
    "name": "Poja Thali 💜",
    "price": "₹399",
    "originalPrice": "",
    "description": "size 4.5 inches aesthetic designs for poja ghar",
    "size": "",
    "image": "poja-thali-2.png",
    "imageSmall": "poja-thali-2-sm.png",
    "extraImages": [],
    "categories": [
      "Resin art",
      "Home deco",
      "Festival special",
      "Gift"
    ],
    "whatsappMessage": "buy poja thali"
  },
  {
    "id": "poja-thali-3",
    "name": "Poja Thali 🌊",
    "price": "₹599",
    "originalPrice": "",
    "description": "size 4.5 inches aesthetic designs for poja ghar",
    "size": "",
    "image": "poja-thali-3.jpg",
    "imageSmall": "poja-thali-3-sm.jpg",
    "extraImages": [
      {
        "image": "poja-thali-3-alt1.jpg",
        "imageSmall": "poja-thali-3-alt1-sm.jpg"
      }
    ],
    "categories": [
      "Resin art",
      "Home deco",
      "Festival special",
      "Gift"
    ],
    "whatsappMessage": "buy poja thali"
  },
  {
    "id": "poja-thali-4",
    "name": "Poja Thali",
    "price": "₹599",
    "originalPrice": "",
    "description": "size 4.5 inches aesthetic designs for poja ghar",
    "size": "",
    "image": "poja-thali-4.jpg",
    "imageSmall": "poja-thali-4-sm.jpg",
    "extraImages": [
      {
        "image": "poja-thali-4-alt1.jpg",
        "imageSmall": "poja-thali-4-alt1-sm.jpg"
      }
    ],
    "categories": [
      "Resin art",
      "Home deco",
      "Festival special",
      "Gift"
    ],
    "whatsappMessage": "buy poja thali"
  },
  {
    "id": "poja-thali-5",
    "name": "Poja Thali ❣️",
    "price": "₹549",
    "originalPrice": "",
    "description": "size 4.5 inches aesthetic designs for poja ghar",
    "size": "",
    "image": "poja-thali-5.jpg",
    "imageSmall": "poja-thali-5-sm.jpg",
    "extraImages": [],
    "categories": [
      "Resin art",
      "Home deco",
      "Festival special",
      "Gift"
    ],
    "whatsappMessage": "buy poja thali"
  },
  {
    "id": "poja-thali-6",
    "name": "Poja Thali 💛",
    "price": "₹299",
    "originalPrice": "",
    "description": "size 4.5 inches aesthetic designs for poja ghar",
    "size": "",
    "image": "poja-thali-6.jpg",
    "imageSmall": "poja-thali-6-sm.jpg",
    "extraImages": [],
    "categories": [
      "Resin art",
      "Home deco",
      "Festival special",
      "Gift"
    ],
    "whatsappMessage": "buy poja thali"
  },
  {
    "id": "poja-thali-7",
    "name": "Poja Thali 🌹",
    "price": "₹549",
    "originalPrice": "",
    "description": "size 4.5 inches aesthetic designs for poja ghar",
    "size": "",
    "image": "poja-thali-7.jpg",
    "imageSmall": "poja-thali-7-sm.jpg",
    "extraImages": [],
    "categories": [
      "Resin art",
      "Home deco",
      "Festival special",
      "Gift"
    ],
    "whatsappMessage": "buy poja thali"
  },
  {
    "id": "poja-thali-8",
    "name": "Poja Thali 💝",
    "price": "₹549",
    "originalPrice": "",
    "description": "size 4.5 inches aesthetic designs for poja ghar",
    "size": "",
    "image": "poja-thali-8.jpg",
    "imageSmall": "poja-thali-8-sm.jpg",
    "extraImages": [],
    "categories": [
      "Resin art",
      "Home deco",
      "Festival special",
      "Gift"
    ],
    "whatsappMessage": "buy poja thali"
  },
  {
    "id": "poja-thali-9",
    "name": "Poja Thali 💖",
    "price": "₹399",
    "originalPrice": "",
    "description": "size 4.5 inches aesthetic designs for poja ghar",
    "size": "",
    "image": "poja-thali-9.jpg",
    "imageSmall": "poja-thali-9-sm.jpg",
    "extraImages": [],
    "categories": [
      "Resin art",
      "Home deco",
      "Festival special",
      "Gift"
    ],
    "whatsappMessage": "buy poja thali"
  },
  {
    "id": "poja-thali-10",
    "name": "poja thali 🌺",
    "price": "₹399",
    "originalPrice": "",
    "description": "size 4.5 inches aesthetic designs for poja ghar",
    "size": "",
    "image": "poja-thali-10.jpg",
    "imageSmall": "poja-thali-10-sm.jpg",
    "extraImages": [],
    "categories": [
      "Resin art",
      "Home deco",
      "Festival special",
      "Gift"
    ],
    "whatsappMessage": "buy poja thali"
  },
  {
    "id": "poja-thali-11",
    "name": "poja Thali 💙",
    "price": "₹899",
    "originalPrice": "",
    "description": "size 8.5 inches aesthetic designs for poja ghar",
    "size": "",
    "image": "poja-thali-11.jpg",
    "imageSmall": "poja-thali-11-sm.jpg",
    "extraImages": [],
    "categories": [
      "Resin art",
      "Home deco",
      "Festival special",
      "Gift"
    ],
    "whatsappMessage": "buy poja thali"
  },
  {
    "id": "car-hanging",
    "name": "car hanging",
    "price": "₹399",
    "originalPrice": "",
    "description": "your car’s perfect personalized touch, crafted beautifully to make every drive special. ✨🚗",
    "size": "",
    "image": "car-hanging.jpg",
    "imageSmall": "car-hanging-sm.jpg",
    "extraImages": [
      {
        "image": "car-hanging-alt1.jpg",
        "imageSmall": "car-hanging-alt1-sm.jpg"
      }
    ],
    "categories": [
      "Resin art",
      "Gift",
      "Mirror"
    ],
    "whatsappMessage": "buy car hanging"
  },
  {
    "id": "resin-keychain-6",
    "name": "Resin Keychain",
    "price": "₹299",
    "originalPrice": "",
    "description": "Handmade resin keychain ✨ Customizable, stylish & perfect for gifting or everyday use. 💖",
    "size": "",
    "image": "resin-keychain-6.jpg",
    "imageSmall": "resin-keychain-6-sm.jpg",
    "extraImages": [
      {
        "image": "resin-keychain-6-alt1.jpg",
        "imageSmall": "resin-keychain-6-alt1-sm.jpg"
      }
    ],
    "categories": [
      "Resin art",
      "Gift"
    ],
    "whatsappMessage": "buy keychain"
  },
  {
    "id": "resin-keychain-7",
    "name": "Resin Keychain",
    "price": "₹299",
    "originalPrice": "",
    "description": "Handmade resin keychain ✨ Customizable, stylish & perfect for gifting or everyday use. 💖",
    "size": "",
    "image": "resin-keychain-7.jpg",
    "imageSmall": "resin-keychain-7-sm.jpg",
    "extraImages": [
      {
        "image": "resin-keychain-7-alt1.jpg",
        "imageSmall": "resin-keychain-7-alt1-sm.jpg"
      },
      {
        "image": "resin-keychain-7-alt2.jpg",
        "imageSmall": "resin-keychain-7-alt2-sm.jpg"
      }
    ],
    "categories": [
      "Resin art",
      "Gift"
    ],
    "whatsappMessage": "buy keychain"
  }
];
