// ---------------------------------------------------------------
// AUTO-GENERATED by scripts/sync-products.mjs from the operator's
// Google Sheet + Drive photos. Do not hand-edit — changes here get
// overwritten on the next sync. To update products, edit the sheet.
// Last synced: 2026-09-14T08:32:48.105Z
// ---------------------------------------------------------------

const PRODUCTS = [
  {
    "id": "resin-sketch-wall-panel",
    "name": "Resin Sketch Wall Panel",
    "price": "₹799",
    "description": "A hand-sketched design sealed under clear resin.",
    "size": "",
    "image": "resin-sketch-wall-panel.jpg",
    "imageSmall": "resin-sketch-wall-panel-sm.jpg",
    "extraImages": [
      {
        "image": "resin-sketch-wall-panel-alt1.jpg",
        "imageSmall": "resin-sketch-wall-panel-alt1-sm.jpg"
      },
      {
        "image": "resin-sketch-wall-panel-alt2.jpg",
        "imageSmall": "resin-sketch-wall-panel-alt2-sm.jpg"
      }
    ],
    "categories": [
      "Painting sketch"
    ],
    "whatsappMessage": "Hi! I'm interested in the Resin Sketch Wall Panel — can you share more details?"
  },
  {
    "id": "abstract-resin-pour-art",
    "name": "Abstract Resin Pour Art",
    "price": "₹1,199",
    "description": "A free-flowing abstract resin pour in layered color.",
    "size": "",
    "image": "abstract-resin-pour-art.jpg",
    "imageSmall": "abstract-resin-pour-art-sm.jpg",
    "extraImages": [
      {
        "image": "abstract-resin-pour-art-alt1.jpg",
        "imageSmall": "abstract-resin-pour-art-alt1-sm.jpg"
      }
    ],
    "categories": [
      "Resin art"
    ],
    "whatsappMessage": "Hi! I'm interested in the Abstract Resin Pour Art — can you share more details?"
  },
  {
    "id": "lippan-mirror-wall-art",
    "name": "Lippan Mirror Wall Art",
    "price": "₹1,499",
    "description": "Traditional Lippan mud-mirror work, hand finished.",
    "size": "",
    "image": "lippan-mirror-wall-art.jpg",
    "imageSmall": "",
    "extraImages": [],
    "categories": [
      "Lippan art"
    ],
    "whatsappMessage": "Hi! I'm interested in the Lippan Mirror Wall Art — can you share more details?"
  },
  {
    "id": "mosaic-resin-wall-piece",
    "name": "Mosaic Resin Wall Piece",
    "price": "₹999",
    "description": "A mosaic-tiled resin piece made for wall display.",
    "size": "",
    "image": "mosaic-resin-wall-piece.jpg",
    "imageSmall": "",
    "extraImages": [],
    "categories": [
      "Mosaic art"
    ],
    "whatsappMessage": "Hi! I'm interested in the Mosaic Resin Wall Piece — can you share more details?"
  },
  {
    "id": "resin-trinket-tray",
    "name": "Resin Trinket Tray",
    "price": "₹599",
    "description": "A small catch-all tray finished with a glossy resin seal.",
    "size": "",
    "image": "resin-trinket-tray.jpg",
    "imageSmall": "",
    "extraImages": [],
    "categories": [
      "Home deco"
    ],
    "whatsappMessage": "Hi! I'm interested in the Resin Trinket Tray — can you share more details?"
  },
  {
    "id": "shubh-labh-door-hanging",
    "name": "Shubh Labh Door Hanging",
    "price": "₹399",
    "description": "A festive door plaque for Diwali and other celebrations.",
    "size": "",
    "image": "shubh-labh-door-hanging.jpg",
    "imageSmall": "",
    "extraImages": [],
    "categories": [
      "Festival special"
    ],
    "whatsappMessage": "Hi! I'm interested in the Shubh Labh Door Hanging — can you share more details?"
  },
  {
    "id": "resin-keepsake-gift-set",
    "name": "Resin Keepsake Gift Set",
    "price": "₹699",
    "description": "A boxed gift set of small resin keepsakes.",
    "size": "",
    "image": "resin-keepsake-gift-set.jpg",
    "imageSmall": "",
    "extraImages": [],
    "categories": [
      "Gift"
    ],
    "whatsappMessage": "Hi! I'm interested in the Resin Keepsake Gift Set — can you share more details?"
  },
  {
    "id": "resin-framed-mirror",
    "name": "Resin Framed Mirror",
    "price": "₹1,299",
    "description": "A decorative mirror framed in hand-poured resin.",
    "size": "",
    "image": "resin-framed-mirror.jpg",
    "imageSmall": "",
    "extraImages": [],
    "categories": [
      "Mirror"
    ],
    "whatsappMessage": "Hi! I'm interested in the Resin Framed Mirror — can you share more details?"
  }
];
